FROM node:6-alpine

ENV NODE_ENV production
ENV GHOST_BASE /app/ghost/
ENV GHOST_CONTENT /app/ghost/content

ENV GHOST_VERSION 1.17.3

#ENV GHOST_VERSION 0.11.12

WORKDIR $GHOST_BASE

# install ghost using sqlite during build phase as mysql is not yet present
RUN npm install -g ghost-cli &&\
    ghost install "$GHOST_VERSION" \
        --db sqlite3 \
        --no-prompt --no-stack --no-setup \
        --dir "$GHOST_BASE"
#    ghost config config.production.json "$GHOST_BASE/config.development.json" &&\


#RUN  node ghost install "$GHOST_VERSION" --db mysql --no-prompt --no-stack --no-setup --dir "$GHOST_BASE"
## &&\
#RUN node ghost config --ip 0.0.0.0 --port 2368 --no-prompt --db mysql --url mysql://root@db/ghost_tech &&\
#	node ghost config paths.contentPath "$GHOST_CONTENT" &&\
#	node ln -s config.production.json "$GHOST_BASE/config.development.json" &&\
#	readlink -f "$GHOST_BASE/config.development.json" &&\
#	mv "$GHOST_CONTENT" "$GHOST_BASE/content.orig" &&\
#	mkdir -p "$GHOST_CONTENT" &&\
#	chown node:node "$GHOST_CONTENT" &&\
#	"$GHOST_BASE/current/node_modules/knex-migrator/bin/knex-migrator" --version

#RUN apk add --no-cache \
#		ca-certificates \
#		openssl &&\
#    apk add --no-cache --virtual build-deps \
#		gcc \
#		make \
#		python \
#		unzip &&\
#    unzip Ghost-$GHOST_VERSION.zip &&\
#    rm -rf Ghost-$GHOST_VERSION.zip &&\
#    npm install --production &&\
#	apk del build-deps &&\
#	npm cache clean &&\
#    rm -rf /tmp/npm* &&\
#	mkdir -p $GHOST_CONTENT &&\
#	ln -s $GHOST_CONTENT/config.js $GHOST_BASE/config.js
#
VOLUME $GHOST_CONTENT

ARG BUILD_VERSION
RUN echo $BUILD_NUMBER && apk --no-cache update

EXPOSE 2368
CMD ["node", "index.js"]
