FROM node:6-alpine

EXPOSE 2368

ENV NODE_ENV production
ENV GHOST_BASE /app/ghost
ENV GHOST_CONTENT /app/ghost/content

ENV GHOST_VERSION 1.17.3

WORKDIR $GHOST_BASE

# install ghost using sqlite during build phase as mysql is not yet present
RUN npm install -g ghost-cli &&\
    ghost install "$GHOST_VERSION" \
        --db sqlite3 \
        --no-prompt --no-stack --no-setup \
        --dir "$GHOST_BASE" &&\
    rm -rf $GHOST_BASE/current/content/images &&\
    ln -s $GHOST_BASE/content/config.production.json $GHOST_BASE/current/config.production.json &&\
    ln -s $GHOST_BASE/content/images $GHOST_BASE/current/content/images

WORKDIR $GHOST_BASE/current

CMD ["node", "index.js"]
