version: "3.2"
services:
  ghost:
    deploy:
      resources:
        limits:
          cpus: '0.5'
    build:
      context: .
      dockerfile: Dockerfile.1
    image: revenant/ghost1
    environment:
      - TZ=US/Mountain
    volumes:
      - /data/ghost/surfing1/content:/app/ghost/content
      - /data/ghost/surfing1/config:/app/ghost/config
    #entrypoint: sleep 900000
    ports:
      - target: 2368
        published: 2001
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
#        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
        delay: 5s
#        max_attempts: 3
#        window: 120s

  db:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /data/ghost/surfing1/db:/var/lib/mysql
